### ISSUE TITLE
Login Screen - remove credentials, replace with copy

### ISSUE THREAD

**Issue by acidjazz** [maxanet/uploader#10]

**Comment by brookeberger** [comment]
Here's what I'm thinking - feel free to make suggestions 

Maxanet Uploader

Upload auction photos & item information quickly & easily from your mobile device or tablet
Button says: Get Started

**Comment by acidjazz** [comment]
![image](https://user-images.githubusercontent.com/967369/43536870-5a4a0918-9583-11e8-869f-bee31d3591ea.png)
