### ISSUE TITLE
Production Rollout Tasks

### ISSUE THREAD

**Issue by acidjazz** [maxanet/uploader#5]
* [x] Remove defaults for FTP data and user login
* [x] Replace actual CSV post response with decided copy

**Comment by danstanton2** [comment]
Hey Kevin - a little unsure about #5 here. Any more info? Thanks - Dan

**Comment by acidjazz** [comment]
@danstanton2 This is a list of things we have to do in the app when we are happy with it and want to go live.  You'll see what I mean by defaults when you install the next build
